### PR TITLE
Optionally support JSON Schema validation

### LINKED ISSUE #27: Schema validation
Ability to validate a target JSON file against a JSON schema definition file

### PR DESCRIPTION
**Pull request by prantlf**
JSON Schema allows semantic validation in addition to the syntax check.

Attempts to fix #27.

This PR is based on the branch [prantlf/upgrade-dependencies](https://github.com/prantlf/grunt-jsonlint/commits/upgrade-dependencies), which replaced [`jsonlint`](https://www.npmjs.com/package/jsonlint) with [`@prantlf/jsonlint`](https://www.npmjs.com/package/@prantlf/jsonlint).

### CODE REVIEW

**Comment by brandonramirez** [comment]
Thank you for this contribution.  Schema validation has been on the roadmap for years and I've never had the time to work on it.

**Comment by prantlf** [comment]
Yes, I'll add the negative test.

**Comment by prantlf** [comment]
I added the negative test and fixed a problem with schema error printing. (I'm a little father with my for, than the PRs I've opened until now and I covered the problem by other code - I show both line and column.) The problem is, that the schema validator doesn't report the location. Or I didn't figure out how to enable it. I'd like to look at it once more, because it makes the error analysis more difficult. 

I got into trouble with merging your changes. I should've told you the order of merging the pull requests earlier. In the end, I resolved the conflicts but I had to resort to as forced push to this PR branch. It's better to look at the change as whole instead of comparing the shingle commits., I'm sorry.

**Comment by brandonramirez** [comment]
Thank you!  This looks great.

Sorry for the merge troubles.  The PR's included common changes, so I was doomed to experience conflicts no matter what order I merged them in.

I then caused you some merge conflicts by updating the linter.

Sorry for that.  I think we landed in a good place.

I really appreciate all the effort you've put into these changes.  This is why I love open source!

**Pull request merged**
