### PR TITLE
Create .travis.yml

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by paladox** [comment]
Please allow testing this repo at https://travis-ci.org/

**Comment by brandonramirez** [comment]
Funny... I was just looking at my travis-ci builds and realized this project wasn't there.  I was considering adding it shortly.

Thanks for doing this for me!  You've been a big help.

**Comment by paladox** [comment]
Thanks.

**Comment by brandonramirez** [comment]
At some point I want to setup a negative test as well.  The only automated test in place is that a good file validates correctly.  There are no tests in place to verify that a bad file fails validation.  I'll try to set that up later as I think it would be very useful.

**Comment by paladox** [comment]
Ok thanks.

**Pull request merged**
