### PR TITLE
Add a "cjson" option to allow the ability to parse cjson

### PR DESCRIPTION
**Pull request by fredghosn**

### CODE REVIEW

**Comment by brandonramirez** [comment]
What a fantastic idea for a new feature.  Thank you so much for implementing it along with an effective unit test.

This is merged and will be in the next release.

**Comment by acatl** [comment]
first of all great plugin! 

this new commit is awesome! I was holding back on using this linter because we have our JSON with comments, @brandonramirez any idea when this will get published to NPM?

**Comment by brandonramirez** [comment]
My plan was to put it into the 1.0.6 release along with a few other changes.  But if getting this into NPM is valuable to you, I could just release 1.0.6 with this change alone later today and defer the other changes to a future release.

So I'll have this done later today.

**Comment by brandonramirez** [comment]
@fredghosn Would you like me to add you to the contributors list?

**Comment by fredghosn** [comment]
Sure! Thanks!

**Comment by acatl** [comment]
thanks @brandonramirez!

**Comment by brandonramirez** [comment]
@acatl This has been released to npm as v1.0.6.

**Pull request merged**
